-- Catálogo inicial de Variedades Teresita
insert into public.products (id,name,category,price_usd,icon,active) values
(1,'Tequeños (Bandeja)','Combos y Refrescos',2.0,'🥖',true),
(2,'Combo Escolar','Combos y Refrescos',1.0,'🎒',true),
(3,'Pastelitos (Unidad)','Combos y Refrescos',2.2,'🥟',true),
(4,'Refresco 350ml','Combos y Refrescos',0.65,'🥤',true),
(5,'Coca-Cola 1L','Combos y Refrescos',1.1,'🥤',true),
(6,'Refresco Retornable','Combos y Refrescos',1.0,'🍾',true),
(7,'Refresco 1.5L','Combos y Refrescos',1.6,'🥤',true),
(8,'Coca-Cola 2L','Combos y Refrescos',1.8,'🥤',true),
(9,'Jugo del Valle 500ml','Combos y Refrescos',0.82,'🧃',true),
(10,'Jugo del Valle 1.5L','Combos y Refrescos',1.67,'🧃',true),
(11,'Jugo P Frubys','Combos y Refrescos',0.7,'🧃',true),
(12,'Jugo Ufresh','Combos y Refrescos',0.6,'🧃',true),
(13,'Jugo Frubys Grande','Combos y Refrescos',1.2,'🧃',true),
(14,'Powerade Deportivo','Combos y Refrescos',1.8,'⚡',true),
(15,'Malta 1.5L','Combos y Refrescos',2.15,'🍺',true),
(16,'Malta Polar 355ml','Combos y Refrescos',1.1,'🍺',true),
(17,'Agua Mineral 600ml','Combos y Refrescos',0.6,'💧',true),
(18,'Helados EFE','Combos y Refrescos',1.2,'🍦',true),
(19,'Salsa Especial para Pastelitos','Combos y Refrescos',0.4,'🥫',true),
(20,'Chorizo Ahumado','Charcutería',8.0,'🌭',true),
(21,'Salchicha Paquete (22)','Charcutería',6.0,'🌭',true),
(22,'Salchicha (1 Unidad)','Charcutería',0.27,'🌭',true),
(23,'Queso Blanco Llanero (1kg)','Charcutería',9.0,'🧀',true),
(24,'Nata Criolla','Charcutería',4.0,'🥣',true),
(25,'Mortadela Especial','Charcutería',6.5,'🥓',true),
(26,'Jamón de Pierna','Charcutería',7.5,'🥩',true),
(27,'Jamón Arepero','Charcutería',8.5,'🥪',true),
(28,'Medio Cartón de Huevos (15 un)','Charcutería',3.8,'🥚',true),
(29,'Cartón de Huevos (30 un)','Charcutería',7.6,'🥚',true),
(30,'Huevo por Unidad','Charcutería',0.25,'🥚',true),
(31,'Ibuprofeno 400mg','Fármacos',0.2,'💊',true),
(32,'Amoxicilina 500mg','Fármacos',0.28,'💊',true),
(33,'Vitamina C Efervescente','Fármacos',3.0,'🍊',true),
(34,'Noxpirin Cápsulas','Fármacos',0.75,'💊',true),
(35,'Cetirizina 10mg','Fármacos',0.15,'💊',true),
(36,'Ciprofloxacina 500mg','Fármacos',2.2,'💊',true),
(37,'Diclofenac Potásico','Fármacos',0.15,'💊',true),
(38,'Metronidazol 500mg','Fármacos',0.24,'💊',true),
(39,'Omeprazol 20mg','Fármacos',0.18,'💊',true),
(40,'Acetaminofén 500mg','Fármacos',0.15,'💊',true),
(41,'Doritos Mega Queso','Chucherías',1.3,'🔺',true),
(42,'De Todito Mix','Chucherías',1.3,'🍿',true),
(43,'Pepito Clásico','Chucherías',0.9,'🌽',true),
(44,'Tozimix','Chucherías',0.35,'🥓',true),
(45,'Tradicionales','Chucherías',0.4,'🍟',true),
(46,'Gomitas Trululu','Chucherías',0.1,'🍬',true),
(47,'Cheesetris','Chucherías',1.1,'🧀',true),
(48,'Platanito Natuchips','Chucherías',0.6,'🍌',true),
(49,'Revolcones Ácidos','Chucherías',0.09,'🍭',true),
(50,'Raquetí','Chucherías',0.7,'🥨',true),
(51,'Lisitaz','Chucherías',0.25,'🥨',true),
(52,'Galletas Brinky','Chucherías',0.35,'🍪',true),
(53,'Flips Chocolate','Chucherías',0.85,'🍫',true),
(54,'Nucita Crunch','Chucherías',0.95,'🌰',true),
(55,'Maxcoco Galleta','Chucherías',0.7,'🥥',true),
(56,'Chupeta Bon Bon Bum','Chucherías',0.2,'🍭',true),
(57,'Galletas Saltitacos','Chucherías',0.6,'🍘',true),
(58,'Galleta Rellena','Chucherías',0.8,'🍪',true),
(59,'Galleta María Ind. Unidad','Chucherías',0.14,'🍪',true),
(60,'Galleta María Ind. Paquete','Chucherías',1.3,'🍪',true),
(61,'Galleta María IT Unidad','Chucherías',0.12,'🍪',true),
(62,'Galleta María IT Paquete','Chucherías',1.2,'🍪',true),
(63,'Caramelo Splot','Chucherías',0.3,'🍬',true),
(64,'Splot Ojos Dulce','Chucherías',0.055,'👀',true),
(65,'Chicle Revolcón','Chucherías',0.09,'🍬',true),
(66,'Cheeseking','Chucherías',0.6,'🧀',true),
(67,'Chesitos','Chucherías',0.35,'🧀',true),
(68,'Boli Bulls Chicle','Chucherías',0.35,'🔴',true),
(69,'Cigarro por Unidad','Chucherías',0.079,'🚬',true),
(70,'Cigarro Cajetilla','Chucherías',1.59,'🚬',true),
(71,'Arroz Blanco 1kg','Víveres',1.3,'🍚',true),
(72,'Pasta Larga 1kg','Víveres',1.62,'🍝',true),
(73,'Pasta Corta 1kg','Víveres',1.32,'🍲',true),
(74,'Harina Mimasa 1kg','Víveres',0.95,'🌽',true),
(75,'Harina Juana 1kg','Víveres',1.2,'🫓',true),
(76,'Azúcar Refinada 1kg','Víveres',1.7,'🧂',true),
(77,'Sal Marina 1kg','Víveres',0.7,'🧂',true),
(78,'Aceite Mirasol','Víveres',1.5,'🌻',true),
(79,'Mantequilla Mavesa 500g','Víveres',1.8,'🧈',true),
(80,'Mayonesa Kraft 445g','Víveres',2.6,'🍶',true),
(81,'Mayonesa 500g','Víveres',2.66,'🍶',true),
(82,'Salsa de Tomate Pampero','Víveres',2.0,'🍅',true),
(83,'Café Molido Fama 250g','Víveres',1.45,'☕',true),
(84,'Jugo en Polvo Boka','Víveres',0.45,'🧃',true),
(85,'Aceite Vegetal 900ml','Víveres',3.0,'🫒',true),
(86,'Aceite Vegetal 250ml','Víveres',1.5,'🫒',true),
(87,'Salsa Negra / Inglesa','Víveres',1.82,'🍾',true),
(88,'Leche en Polvo Completa','Víveres',3.9,'🥛',true),
(89,'Mayonesa en Teta','Víveres',0.25,'🍶',true),
(90,'Mostaza Preparada','Víveres',0.25,'🌭',true),
(91,'Aliño Preparado','Víveres',0.35,'🌿',true),
(92,'Ajo en Pasta','Víveres',0.24,'🧄',true),
(93,'Cubito Maggi','Víveres',0.15,'🧊',true),
(94,'Desodorante Roll-on','Higiene',0.7,'🧴',true),
(95,'Crema Dental Colgate','Higiene',1.8,'🪥',true),
(96,'Pañal Desechable Unidad','Higiene',0.4,'👶',true),
(97,'Toallas Sanitarias','Higiene',0.15,'🌸',true),
(98,'Baño de Crema Nutribella','Higiene',1.35,'💆',true),
(99,'Jabón Alive','Higiene',0.7,'🧼',true),
(100,'Jabón Líquido Lemon','Higiene',1.1,'🍋',true),
(101,'Champú Liso Extremo','Higiene',1.35,'🧴',true),
(102,'Champú Sachet','Higiene',0.6,'🧴',true),
(103,'Jabón Las Llaves Panela','Higiene',1.1,'🧼',true),
(104,'Papel Higiénico (4 rollos)','Higiene',2.5,'🧻',true),
(105,'Papel Higiénico Individual','Higiene',0.6,'🧻',true),
(106,'Rasuradora Doble Hoja','Higiene',1.6,'🪒',true),
(107,'Rasuradora Económica','Higiene',0.32,'🪒',true),
(108,'Suavizante de Ropa','Higiene',1.0,'🧺',true),
(109,'Jabón Especial de Tocador','Higiene',1.15,'🧼',true),
(110,'Limpiador 3B 400ml','Higiene',1.3,'✨',true)
on conflict (id) do update set name=excluded.name, category=excluded.category, price_usd=excluded.price_usd, icon=excluded.icon, active=excluded.active;
