-- Variedades Teresita - Supabase
create table if not exists public.products (
  id bigint primary key,
  name text not null,
  category text not null,
  price_usd numeric(12,3) not null default 0,
  price_bs numeric(14,2),
  sold_out boolean not null default false,
  icon text,
  image_url text,
  active boolean not null default true,
  updated_at timestamptz not null default now()
);

alter table public.products add column if not exists image_url text;
alter table public.products add column if not exists price_bs numeric(14,2);
alter table public.products add column if not exists sold_out boolean not null default false;

create table if not exists public.store_settings (
  id bigint primary key default 1 check (id = 1),
  rate numeric(12,4) not null default 873.87,
  updated_label text not null default 'hoy',
  updated_at timestamptz not null default now(),
  force_open boolean not null default false
);

alter table public.store_settings add column if not exists force_open boolean not null default false;

create table if not exists public.rate_history (
  id bigint generated by default as identity primary key,
  rate numeric(12,4) not null,
  updated_label text not null,
  created_at timestamptz not null default now()
);

alter table public.products enable row level security;
alter table public.store_settings enable row level security;
alter table public.rate_history enable row level security;

-- Clientes: solo lectura.
create policy "Public can read active products" on public.products
for select to anon, authenticated using (active = true);
create policy "Public can read store settings" on public.store_settings
for select to anon, authenticated using (true);

-- Administradores autenticados: lectura/escritura.
create policy "Admins can manage products" on public.products
for all to authenticated using (true) with check (true);
create policy "Admins can manage settings" on public.store_settings
for all to authenticated using (true) with check (true);
create policy "Admins can read history" on public.rate_history
for select to authenticated using (true);
create policy "Admins can add history" on public.rate_history
for insert to authenticated with check (true);

insert into public.store_settings (id, rate, updated_label)
values (1, 873.87, 'hoy')
on conflict (id) do nothing;

-- Después de crear las tablas, importa los 110 productos del catálogo desde el panel o ejecuta
-- el INSERT generado por la herramienta de migración del proyecto.
